# Golag
# https://hub.docker.com/_/golang
FROM golang:1 as golang
RUN go get -u github.com/cosmtrek/air
#RUN set -eux && \
#  apk update && \
#  apk add --no-cache git curl && \
#  go get -u github.com/cosmtrek/air && \
#  go build -o /go/bin/air github.com/cosmtrek/air && \
#  go get -u github.com/go-delve/delve/cmd/dlv && \
#  go build -o /go/bin/dlv github.com/go-delve/delve/cmd/dlv

# Nginx
# https://hub.docker.com/_/nginx
FROM nginx:1

WORKDIR /var/www/html

COPY --from=golang /go /go
COPY --from=golang /usr/local/go /usr/local/go
COPY ./app /var/www/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./.bashrc /root/.bashrc

CMD [ "bin/dev" ]