version: '3'

services: 
    sns_sample:
        build: 
            context: . #ビルドに使うDockerFileの場所
            dockerfile: DockerFile #DockerFileの名前
        container_name: sns_sample_api #コンテナ名
        #command: air #app/bin/dev で実行されるから無し
        stdin_open: true
        tty: true #コンテナの永続化
        volumes: 
            - ./app:/var/www/html #appと言うボリュームを/var/www/htmlにマウント
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.bashrc:/root/.bashrc
        #ports:
        #    - 8080:8080
        # environment: 
        #     MYSQL_HOST: mysql
        depends_on: 
            - mysql
            - phpmyadmin
        networks: 
            - sns-sample-network
        environment: 
            - VIRTUAL_HOST=api.sns.sample
        security_opt: 
            - apparmor:unconfied
        cap_add:
            - SYS_PTRACE

    mysql:
        image: mysql:8
        restart: always
        #container_name: sns_mysql
        #ports:
        #    - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sns_sample
            MYSQL_USER: sns_test
            MYSQL_PASSWORD: password
            TZ: 'Asia/Tokyo'
        #command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql:/var/lib/mysql #sqlのデータ
            - ./sql:/sql #sqlディレクトリのクエリ
        cap_add:
            - SYS_NICE #追加
        networks: 
            - sns-sample-network

    phpmyadmin:
        image: phpmyadmin:5
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=sns_test
            - PMA_PASSWORD=password
            - VIRTUAL_HOST=phpmyadmin.sns.sample
        links:
            - mysql
        ports:
            - 8000:80
        #volumes:
        #    - /sessions
        networks: 
            - sns-sample-network

networks:
    sns-sample-network:
        name: sns_sample_network

volumes:
  db-data:
    driver: local