version: '3'

services: 
    sns_sample:
        build: 
            context: . #ビルドに使うDockerFileの場所
            dockerfile: DockerFile #DockerFileの名前
        container_name: sns_sample_api #コンテナ名
        command: /bin/sh -c "go run main.go"
        stdin_open: true
        tty: true #コンテナの永続化
        volumes: 
            - ./app:/app
            -  ./.bashrc:/root/.bashrc
        ports:
            - 8080:8080
        environment: 
            MYSQL_HOST: mysql
        depends_on: 
            - mysql
            - phpmyadmin

    mysql:
        image: mysql:8
        restart: always
        #container_name: sns_mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sns_sample
            MYSQL_USER: sns_test
            MYSQL_PASSWORD: password
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql:/var/lib/mysql #sqlのデータ
            - ./sql:/sql #sqlディレクトリのクエリ
        cap_add:
            - SYS_NICE #追加

    phpmyadmin:
        image: phpmyadmin:5
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=sns_test
            - PMA_PASSWORD=password
        links:
            - mysql
        ports:
            - 8000:80
        #volumes:
        #    - /sessions

volumes:
  db-data:
    driver: local